### ISSUE TITLE
Add readme.md

### ISSUE THREAD

**Issue by nasatome** [nasatome/docker-network-utils#1]
Add readme.md to explain this project

**Comment by ShobhitRathi** [comment]
i can add a read me but what to write under it you have to explain it to me.(like explain about the project so that i can write about it)

**Comment by ShobhitRathi** [comment]
I've added a pull request please check

**Comment by nasatome** [comment]
Greetings, this is a Request that I will accept if you work a lot on it, I need it to be MarkDown type, not HTML and also the following

It's a project dedicated to create a basic and economic infrastructure in a VPS that uses a load balancer, particularly for now is "Traefik" you can look for some traefik information and add it?, explain that this is a modular project: so it will link to different projects that I also have as an example:

Explain that they first need to Hardenize the server with the next project:
`https://github.com/nasatome/First-Steps-and-Hardening-in-Ubuntu-Server-And-Docker`

`https://github.com/nasatome/dockapress`  It's a project to run WordPress with docker
`https://github.com/nasatome/pycorndock` is a project to run Docker Projects with Python, (Django, Flask)
`https://github.com/nasatome/doockla` Docker + Joomla (PHP)
`https://github.com/nasatome/dockavel` Docker + (PHP) Laravel

There must also be internal links to the subreps as they are:
```
./reverse-proxy/traefik
./utility/portainer
```

Explain that ports 80 and 443 need to be open as a requirement

**Comment by ShobhitRathi** [comment]
can you tell me whats the difference between  markdown and HTML type

**Comment by nasatome** [comment]
This is the best explanation
`https://guides.github.com/features/mastering-markdown/`

**Comment by ShobhitRathi** [comment]
Sure ill start working on it tomorrow. 
Hope you don't require it very urgently.

**Comment by nasatome** [comment]
Not is Urgent :D thanks
